# Generated by Django 6.0.7 on 2026-07-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_emailotp'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_booking_hours', models.PositiveIntegerField(default=1)),
                ('contact_number', models.CharField(max_length=15)),
                ('amenities', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_types', models.ManyToManyField(related_name='venues', to='venues.eventtype')),
                ('venue_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.venueowner')),
            ],
        ),
    ]
