# Generated by Django 6.0.7 on 2026-08-05 11:41

import django.db.models.deletion
import venues.models.venue_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venueimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(upload_to=venues.models.venue_image.venue_image_path),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='venues.venue')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
