# Generated by Django 6.0.7 on 2026-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venueimage_image_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='minimum_booking_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minimum booking duration in minutes'),
        ),
    ]
