# Generated by Django 6.0.7 on 2026-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_weeklyavailability_delete_availability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyavailability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20),
        ),
    ]
