# Generated by Django 6.0.7 on 2026-08-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_alter_weeklyavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='venues.venue')),
            ],
            options={
                'ordering': ['venue', 'day_of_week'],
                'unique_together': {('venue', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('minimum_booking_duration_minutes', models.PositiveIntegerField(default=60)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('buffer_time_minutes', models.PositiveIntegerField(default=0)),
                ('weekly_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='venues.weeklyschedule')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='WeeklyAvailability',
        ),
    ]
