# Generated by Django 6.0.7 on 2026-08-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_weeklyschedule_weeklytimeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('minimum_booking_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('buffer_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to='venues.venue')),
            ],
            options={
                'unique_together': {('venue', 'date')},
            },
        ),
    ]
