# Generated by Django 6.0.7 on 2026-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
