# Generated by Django 6.0.7 on 2026-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueowner',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
