# Generated by Django 6.0.7 on 2026-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_venueowner_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueowner',
            name='razorpay_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='razorpay_stakeholder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
