# Generated by Django 6.0.7 on 2026-09-02 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_REFUND', 'Payment Refund'), ('MAINTENANCE_CREATED', 'Maintenance Created'), ('EMERGENCY_MAINTENANCE', 'Emergency Maintenance'), ('REVIEW_REPORTED', 'Review Reported'), ('REVIEW_SUSPENDED', 'Review Suspended'), ('REVIEW_RESTORED', 'Review Restored')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
